### ISSUE TITLE
Review: Dedication

### ISSUE THREAD

**Issue by vr8hub** [irontigran/plato_the-dialogues-of-plato_benjamin_jowett#23]
You have done a tremendous job with this, Jacob. I have only looked at it briefly, but it's already clear that the work you've done is … well, tremendous. :) Thank you for your dedication, perseverance, and attention to detail!

As I mentioned on-list, the review is probably going to take several days. I'm going to just create issues as I find them; you are welcome to wait until I'm finished to address any of them, or you are welcome to address them (where "address" might mean correct and might mean disagree with my conclusions :) as we go. Your choice.

There is a dedication [here](https://archive.org/details/b24750189_0001/page/n7/mode/2up) in the first volume that is missing from the production. I've reviewed the entire thread on the list, and don't see anything mentioned about it. Was it left out intentionally or accidentally?

**Comment by irontigran** [comment]
Thanks for the kind words Vince! I'll be trying to address fixes as you bring them up.

I totally missed the dedication; I added it back with this PR: #30
