### ISSUE TITLE
Review: Roman numerals

### ISSUE THREAD

**Issue by vr8hub** [irontigran/plato_the-dialogues-of-plato_benjamin_jowett#25]
- [x] There are several instances of roman numerals in the endnotes with periods following them. These weren't caught by lint because what follows are decimal numbers rather than lowercase letters. There is also an instance in "Apology" (_Republic_ VI. 492).

**Comment by irontigran** [comment]
Should be resolved by the linked PR.

**Comment by vr8hub** [comment]
The PR fixes the one in "Apology," but not the ones in the endnotes.

**Comment by irontigran** [comment]
Moving too quickly, sorry. The PR should now take care of all instances that aren't being used to number a paragraph or section.
