### ISSUE TITLE
Review: Metadata

### ISSUE THREAD

**Issue by vr8hub** [irontigran/plato_the-dialogues-of-plato_benjamin_jowett#26]
- [x] David Widger actually has an NACOAF id; `create draft` will now add it automatically if it sees him in the list of transcribers, but I'm sure that change has been since you started. I don't remember what it is, but you can just search for his name on the id.loc.gov site.
- [x] Would you mind putting comments on the transcriptions so we know which is what? With this many, it would be helpful to know so someone doesn't have to open each one to find the one they're looking for. `<!-- Republic -->`, e.g.
- [x] Ditto for the IA scans; can you indicate which dialogues are in each volume? E.g. something like `<!-- Charmides, Lysis, Laches, Protagoras, Euthydemus, Cratylus, Phaedrus, Ion, Symposium -->` for vol. 1. (If there are standard abbreviations for those, those could be used as well.) We want people who are reporting typos to check the scans first, and this will let them know which volume to look in.
- [x] Although it's never been codified in SEMoS, our de facto standard to date has been to only put the first volume of scans in `imprint`; having them all in `colophon` is fine.
- [x] You list both the PG transcriptions and the OLL ones; was there a reason you needed both? If so, can you put a blurb in the production notes about why?

**Comment by irontigran** [comment]
I used OLL to supplement PG because OLL was didn't strip cross references (PG zealously stripped page numbers that referred to _other_ books, not just Plato) and Greek snippets. Also, OLL has a search bar that I used to verify where various Stephanus numbers referred - they preserve the numbering in their edition.

I'll add a note to that effect in the production notes.

**Comment by irontigran** [comment]
Addressed metadata comments in PR #34
