### ISSUE TITLE
Review: Text issues

### ISSUE THREAD

**Issue by vr8hub** [irontigran/plato_the-dialogues-of-plato_benjamin_jowett#27]
- [x] There is a missing scene break in Theaetetus, where the dialog begins ("Socrates begins by asking Theodorus whether…"). We don't differentiate between breaks that have lines and those that don't. I haven't looked yet to see if there are more of these; I only saw this because I was looking at the next item that was close.
- [x] `se find-mismatched-diacritics` identifies some differences, at least some of which should be addressed. For example, in the case of "fa[cç]on", e.g., the `facon de parler` in Theaetatus should be `façon de parler` (it is façon in the scans, but facon in the transcription, so this one is a transcription error). Same for σ[εέ]λας in Cratylus; the scan has accented epsilon, the transcription has unaccented. Since they're transcription errors, they're not editorial commits. I'll let you look at the rest. If there instances where the _scans_ are inconsistent and you have to modify one or more instances, then it should be an editorial commit since it's changing content.
- [x] There are multiple instances in Philebus (e.g. philebus-tr-241) where the text to a link is a page number or page numbers. Since epubs don't have page #s, we don't want to use them for links. The page# should be changed to something resembling "see here". (I believe you had to do something similar for the links in _Art of War_?) If there are others in other dialogs, they should be changed as well. Since this is changing content, this would be an editorial commit as well. (Or, it occurs to me, maybe the "p." refers to something other than page#? In which case do we want to expand it, to prevent confusion?)
- [x] The production notes and your email on the list mentioned expanding the abbreviations, so I don't know if this was intentional. In Philebus there is a link with text of "compare "Parm." 128 and following; I assume this is referencing Parmenides. If that was intentional, then no problem.
- [x] The fractions in Timaeus introduction are inconsistent with the spaces between the numbers. The whole numbers have spaces after the commas before the whole number, the fractions don't. 
- [x] There is an extraneous `<br/>` and white space before the `</p>` in Republic, before the `<hr/>` before "There still remains to be considered…".
- [ ] The formatting of the "theses" in "Parmenides" doesn't look quite right. In the scans, each pair of statements is indented to the same level, which "center" doesn't accomplish. Thus, the "I. One is." and "II. One is not." should be indented to the same point, the next two lines to a different point, etc. It looks more along the lines of what we do with the iX classes for verse/song, i.e. indent to a certain level, with each level increasing the indent. That type of formatting also fixes what happens with lines that wrap.
- [x] In instances where dialogs are mentioned followed by punctuation, quoting the dialog should only include commas and periods inside the quotes; other punctuation should be outside. Thus, `… to regard the “Timaeus,”` but `by the help of Republic or “Phaedrus”:`. This is in keeping with CMS, which governs us for everything SEMoS doesn't directly address.
- [x] We do not generally keep "beginning of chapter" text decorations, e.g. small caps on the first word/few words, drop caps, etc. Thus, in Republic, we don't need the first word of each book to be small-capped.
- [x] I saw the discussion about dramatis personae and the decision to format them as our plays, but then shouldn't we also use our dramatis CSS? See SEMoS section [7.6.7.4](https://standardebooks.org/manual/1.6.4/single-page#7.6.7.4).

**Comment by irontigran** [comment]
Re: page numbers. I'll double check the instances, but in general your instinct that "p." refers to something other than page numbers is kind of correct. 

When citing Plato, it's common to use [Stephanus numbers](https://www.plato-dialogues.org/faq/faq007.htm), and Jowett uses them consistently. When he refers to a Stephanus number as a "page",  he is technically correct - it's a page of Henri Estienne's (Stephanus') edition of Plato. Usually, most scholars don't refer to Stephanus numbers as "page numbers" though (and Jowett is inconsistent about it throughout the translation).

Taking all of that into account, I left Jowett's occasional habit of labeling a Stephanus number as a "page number" alone.

**Comment by vr8hub** [comment]
So, a Stephanus reference of 247D is the same as p. 247 D? IOW, all Stephanus refs are page #’s, they just usually don’t have the p. in front?

If so, I’ll put this on the Alex list, but I’m pretty confident he’s going to want those standardized and the p. removed, if for no other reason than everyone else is going to have the same question I had. :)

**Comment by irontigran** [comment]
Addressing each comment (PR #35):

1. "Missing scene break" - fixed
2. "Mismatched diacritics" - I only fixed the two you pointed out; after comparing the scans, I'm comfortable saying that the other diacritics (or lack of) are correct.
3. "Page numbers / Stephanus numbers" - I'll be curious to see what Alex says. The Stephanus number references are not standardized at all as is. Your example could be written as "247 D", "247D", "247", "p. 247", "247 - 250", "247 C, D", "247 C - 250 A". It will definitely be a bit of job to write a script that will clean all of them up correctly.
4. "Parm. abbreviation" - I missed "Parm." in my massive list of abbreviations to expand, so that's fixed now.
5. "Spaces between fractions" - fixed.
6. "Extraneous \<br>" - fixed.
7. "Parmenides theses" - I'll have to come back to this one after looking at what the CSS for verse/song looks like.
8. "Dialogues followed by punctuation" - fixed a lot of errors, since I consistently got this wrong throughout the production.
9. "Beginning of chapter text decorations" - removed.
10. "Dramatic CSS" - added. (I blame this on how many times I edited the CSS to either be up to date with the manual or when I had to remove no-longer-used CSS.)

**Comment by vr8hub** [comment]
I went ahead and checked off the ones you addressed. You can do that as you do things in other issues if you want; it's an easy way to keep track of what is done and what isn't.
For the CSS, you don't want _exactly_ the verse iX CSS, but the general idea, i.e. where the indent is specified, and the padding is such that when it wraps, it wraps in from the left margin of the text.
For the references, the good news is that there aren't any 247D type references, i.e. a search for [0-9]+[A-Z] doesn't turn up anything. While I think it would be nice if the references were standardized, it might not always be possible, e.g. _Republic_ III 386, 387 probably doesn't the letters because it's referring to the entire text on the page rather than a particular section. I don't think we need to worry about that, but I definitely think we need to get rid of the p. (and P., pp., etc.) because of the confusion factor. And that should be pretty easy with a regex.
I have also seen another abbreviation that wasn't expanded; if you meant to expand them all, I'll note any others I find.

**Comment by vr8hub** [comment]
The other abbreviation I saw was "Crit." (Critias?), and then a regex search turned up one more in note-319, Euthyd.

**Comment by irontigran** [comment]
I think I've addressed all the issues that I can (the rest are marked for Alex's review). Are you still working through your review?

**Comment by vr8hub** [comment]
Yes, sorry, Jacob. Our kids have been in from out-of-the-country, and so I've been having to do this after they go to bed, and then they left (for a bit) Monday and we've had social engagements both the last two nights. I'm just now getting to the things that are part of a normal review; the stuff I've found so far I found by just browsing around. I hope to be done by this weekend!

**Comment by vr8hub** [comment]
As you saw on Alex's issue, for the thesis, each line should be it's own paragraph (`<p>`); we only use `<br/>` when it's separating a single sentence. As you convert them, tag each paragraph with the appropriate class for formatting.

**Comment by vr8hub** [comment]
And, last, let's do get rid of the "p[p]." on the references.

**Comment by irontigran** [comment]
Just to make sure I understand re: theses - we're looking for a structure like this?:

```html
<p class="class-that-defines-indentation">I. One is.</p>
<!-- snipped -->
<p class="class-that-defines-indentation">Either one is one,
<br/>
Or, one has being,</p>
<p class="continued">from which opposite consequences are deduced,</p>
<!-- snipped -->
```

**Comment by vr8hub** [comment]
Right. Essentially, any sentence should be a `<p>`. A `<br/>` should only be used within a sentence, as "Either one is one…". And, unlike our verse formatting, when used like this the `<br/>` doesn't have to go on its own line, it can just be at the end of line to be broken. (This sort of formatting is pretty common in dedications, e.g.)
````
<p class="whatever">Either one is one,<br/>
Or, one has being,</p>
````

**Comment by irontigran** [comment]
I updated the Parmenides xhtml and CSS. One thing to note - it doesn't look like we can control the indentation after the `<br/>` element? My reader renders it like this (note how the line after the `<br/>` is not indented to the same level):

![br-element-indent](https://user-images.githubusercontent.com/22407135/174616000-b0b12c75-b6da-4962-b33d-da14805ab628.png)

I'm not great at CSS, but my searches have mostly come up with the answer "if you want to control the indentation after a `<br/>` element, you're using it wrong. Use a `<p>` instead." (See this [stackoverflow discussion](https://stackoverflow.com/questions/28380972/can-i-indent-after-a-line-break))

**Comment by vr8hub** [comment]
Yeah, essentially the line break does exactly what would happen if it had to have a natural line break. And, as you've seen, trying to target `<br/>` is an exercise in futility.
I think you'll just have to make both of those lines `<p>`.

**Comment by irontigran** [comment]
Okay, I've pushed my final changes. I'll close this issue (and the Alex review as well), so I think this can be released unless you or Alex have any other comments.
