### ISSUE TITLE
Review: for Alex

### ISSUE THREAD

**Issue by vr8hub** [irontigran/plato_the-dialogues-of-plato_benjamin_jowett#29]
@acabal, a few questions for you.
- [x] I don't recall this coming up before. Do you care whether we use nth-of-type(1) and nth-of-type(some-big-number) rather than first-of-type and last-of-type?
- [x] In [Timeus](https://archive.org/details/b24750189_0003/page/354/mode/1up), there are numbers with overbars. Currently that's done with with an overstrike character, but that has a couple of side effects: one, if a font with old-style numbers is being used, those numbers are not old-style, so they look out of place in the sequence, and two, the two-digit number 27 has individual bars over each number, instead of a continuous bar over both (which doesn't mean the same thing, mathematically). Do we care? I experimented with spans on the numbers and CSS that uses text-decoration instead, and it worked, at least in Webkit (including Apple Books) and Mozilla (Firefox).
- [x] There are a couple places in [Parminides](https://archive.org/details/b24750189_0004/page/21/mode/1up) where a thesis needs to be formatted. This is being done right now by targeting a `<p>`, and putting `<br/>` in between the lines (see [here](https://github.com/irontigran/plato_the-dialogues-of-plato_benjamin_jowett/blob/20daedc43cd8d9dba8af46b91547e6d87434cd1c/src/epub/text/parmenides.xhtml#L50), e.g.). That feels wrong to me, since each line is a complete sentence. The alternative is to either put the class on all the lines in the thesis (which seems a little brute force), or perhaps to use a `<div>` to surround the thesis and target that. What are your thoughts?
- [x] Where we have comments in the metadata for the transcriptions and scans, the comment usually (always?) is on a separate line above the transcription/scan being commented on, e.g.
````
<!-- a comment on the following transcription -->
<dc:source>https://archive.org/blahblah</dc:source>
````
Jacob put his inline, and to my surprise, they work, i.e. neither build or epubcheck have a problem with them.
````
<dc:source>https://archive.org/blahblah<!-- a comment on this transcription --></dc:source>
````
I was originally going to ask if we cared about being consistent in our commenting, but based on your recent changes to colophon/imprint for multiple transcriptions/scans, I think we now definitely care about being consistent. So, the new question is, do you think the inline comment would be easier to parse than the separate line above? IOW, if we're going to standardize our comment placement, which way do we want to do it?

**Comment by irontigran** [comment]
The CSS for Parmenides has since been updated. [xhtml](https://github.com/irontigran/plato_the-dialogues-of-plato_benjamin_jowett/blob/master/src/epub/text/parmenides.xhtml#L50), [css](https://github.com/irontigran/plato_the-dialogues-of-plato_benjamin_jowett/blob/master/src/epub/css/local.css#L202)

**Comment by vr8hub** [comment]
Great, thanks, I took the aside I made about that out of the above issue.

**Comment by vr8hub** [comment]
One more, @acabal. Τhere are three instances (bottom of [this](https://archive.org/details/b24750189_0003/page/n87/mode/1up) page, middle of [this ](https://archive.org/details/b24750189_0003/page/150/mode/1up) page, and the bottom of [this](https://archive.org/details/b24750189_0003/page/170/mode/1up) page) in _Republic_ where long sentences are italicized. I think they should be quoted (either with quotes or with `<q>`), Jacob thinks they should be emphasis. What say you?

**Comment by acabal** [comment]
> * I don't recall this coming up before. Do you care whether we use nth-of-type(1) and nth-of-type(some-big-number) rather than first-of-type and last-of-type?

If they are actually first or last then I think it would be clearer to use those instead of some large number, or 1



> * In [Timeus](https://archive.org/details/b24750189_0003/page/354/mode/1up), there are numbers with overbars. Currently that's done with with an overstrike character, but that has a couple of side effects: one, if a font with old-style numbers is being used, those numbers are not old-style, so they look out of place in the sequence, and two, the two-digit number 27 has individual bars over each number, instead of a continuous bar over both (which doesn't mean the same thing, mathematically). Do we care? I experimented with spans on the numbers and CSS that uses text-decoration instead, and it worked, at least in Webkit (including Apple Books) and Mozilla (Firefox).

I think CSS would be better here, not just visually but also in terms of font support in ereaders. Unicode overbar is probably not well supported. However, if you think this is math, then MathML might be appropriate, and it can certainly do this kind of thing pretty easily.

> . So, the new question is, do you think the inline comment would be easier to parse than the separate line above? IOW, if we're going to standardize our comment placement, which way do we want to do it?

Let's leave them above, since that's what all the other ebooks do.

> There are a couple places in [Parminides](https://archive.org/details/b24750189_0004/page/21/mode/1up) where a thesis needs to be formatted. This is being done right now by targeting a <p>, and putting <br/> in between the lines (see [here](https://github.com/irontigran/plato_the-dialogues-of-plato_benjamin_jowett/blob/20daedc43cd8d9dba8af46b91547e6d87434cd1c/src/epub/text/parmenides.xhtml#L50), e.g.). That feels wrong to me, since each line is a complete sentence. The alternative is to either put the class on all the lines in the thesis (which seems a little brute force), or perhaps to use a <div> to surround the thesis and target that. What are your thoughts?

It looks like the source has changed since you wrote this. Now it looks like some kind of poetry formatting is being applied to it. I'm not sure why - this looks like a pretty clear case for a basic `text-align: center`. I agree that complete sentences should be in their own `<p>` and `<br/>` should only be used to create line breaks within one complete sentence (like `Either one is one`.

> One more, @acabal. Τhere are three instances (bottom of [this](https://archive.org/details/b24750189_0003/page/n87/mode/1up) page, middle of [this ](https://archive.org/details/b24750189_0003/page/150/mode/1up)page, and the bottom of [this](https://archive.org/details/b24750189_0003/page/170/mode/1up) page) in Republic where long sentences are italicized. I think they should be quoted (either with quotes or with "), Jacob thinks they should be emphasis. What say you?"

No way to tell. They could be emphasis so let's leave them like that.

**Comment by vr8hub** [comment]
Re Parminides, the tagging and CSS has changed, but not the presence of the `<br/>`, hence the question.
Jacob actually had it text-align: center originally, but I disagree it's a case for it's use and had him change it. The formatting in the scans is in sentence pairs, and each pair is at the same indent level. Using center causes every line to begin at a different place, which removes the visual indication that the pairs go together. Given the nature of the logic being discussed, I think that visual indication is important.
If you feel strongly about it, he can revert the changes.
Either way, we still have the question: apply the class to every line, or put a `<div>` around them and target the div?

**Comment by acabal** [comment]
OK, I see, that's fine. 
We can apply the class to each line, as that way it obviates the need for extra scaffolding markup.

**Comment by vr8hub** [comment]
Grrrr. So sorry, Alex, there was one more.

Jacob mentioned this on-list during the production: references in Plato use [Stephanus numbering](https://en.wikipedia.org/wiki/Stephanus_pagination). These usually look something like 243 A or 385 D, 174–182, etc. The number is referring to a page# in the Stephanus edition, the letter to a vertical position on the page; a range of pages doesn't have a letter for obvious reasons. Jacob has of course converted the links to paragraphs within the production (I don't even want to think about how much work that was.)

However, Jowett occasionally used "p. 243 A" or "pp. 174–182", that is, he left the page abbreviation in the reference. Jacob has left those as well. So, although it is technically still a Stephanus number reference, it now _looks_ like it's a regular page# reference, and of course ebooks don't have page numbers. I think those "p. " should be removed, leaving the reference as "243 A" or "174–182", as with the rest of the references.

**Comment by acabal** [comment]
That sounds like it makes sense, to avoid confusion.
