### ISSUE TITLE
Review: Endnotes

### ISSUE THREAD

**Issue by vr8hub** [irontigran/plato_the-dialogues-of-plato_benjamin_jowett#33]
- [x] In endnote 3, the reference to Bentley's _Works_ should be tagged; "Works" in this instance is the title of a collection of his … works. See [here](https://books.google.com/books?id=8DkCAAAAQAAJ&pg=PR1#v=onepage&q&f=false).
- [x] In endnote 19, is the κ.τ.λ. an abbreviation? If so, it should be tagged as such (we tag even foreign language abbreviations). This should be true throughout, if there are others.
- [x] I'm not sure what, if anything, you want to do about this. As an example, note 24 references Humboldt's _Ueber die Verschiedenheit des menschlichen Sprachbaues_. But that "Ueber" is actually "Über" (see [here](https://books.google.com/books?id=dV4SAAAAIAAJ&pg=PP9#v=onepage&q&f=false)). Now, the scans have Ueber, so this is not a transcription error. I know _why_ they printed Ueber (they went with phonetics rather than accuracy in characters), but … Do we care? I'm not sure.

**Comment by irontigran** [comment]
κ.τ.λ. is an abbreviation that is roughly equivalent to "etc." (https://en.wiktionary.org/wiki/%CE%BA%CE%B1%CE%B9_%CF%84%CE%B1_%CE%BB%CE%BF%CE%B9%CF%80%CE%AC).

I've marked all instances of it as an abbreviation.

**Comment by irontigran** [comment]
I don't really have an opinion on Ueber vs. Über, other than being inclined to leave it the same as the scans. Would that count as an editorial change?

**Comment by vr8hub** [comment]
It would be (editorial), but I'm fine if you want to leave it.

**Comment by irontigran** [comment]
Ended up adding the umlaut - I've done a lot of editorial commits in the name of making references easier to google for the reader, and this seems to be in the same line of reasoning.
