### ISSUE TITLE
Review: Publications

### ISSUE THREAD

**Issue by vr8hub** [irontigran/plato_the-dialogues-of-plato_benjamin_jowett#36]
Something I did with Gibbon's references was to pull an extract of everything with an se:name.publication tag, then sort and dedupe them, and see what popped out. Doing that here shows a couple of things.
- [x] There is a reference to _Republics_ (plural). It looks like it's in the scans, so I don't know if that should be standardized or not.
- [x] There are references to both Hippolytus and Hyppolytus. Scans or no, we should standardize the spelling (unless by the remotest chance those are actually two different works?). Wiki says Hippolytus, but I have no idea if that's definitive. This would be editorial since it's changing content.
- [x] This one will require a bit more work (it doesn't help, but I do feel your pain). Capitalization of non-English publications follows different rules than English ones. You can search and see if you can find the CMS reference (in the 17th ed., e.g., Latin is in 11.54); but roughly Latin is sentence case except for proper nouns/adjectives (so _De civitate Dei_), German capitalizes nouns and words used as nouns, and both capitalize the first word. As I found in Gibbon, Jowett is all over the place in his handling (and is often wrong), so the references need to be correctly capitalized. (I've occasionally had to do the same for English ones, so this is no different.) Also editorial.
- [x] That also turned up some more abbreviations, e.g. "de Amicit.", "Hist. of Isr.", "Legg.", "Proc. of the Philol. Society", "P.L." (for Paradise Lost). Again, not sure if you were trying to expand everything, so I'll leave it with you if you want to address them or not. Also editorial.

**Comment by irontigran** [comment]
In the vein of standardizing references: Aristotle's [Sophistical Refutations](https://en.wikipedia.org/wiki/Sophistical_Refutations) is referred to as both _De sophisticis elenchis_ and _Sophistici elenchi_ (After I've corrected both to Latin capitalization rules). Based on a half hour of searching, both forms seem to used the same amount. Should I pick one as the standard form or just leave them both?

**Comment by irontigran** [comment]
Re: _Republics_. That is correct - the context is referring to the multiple works titled _Republic_ or something similar written by various ancient Greek authors.

**Comment by vr8hub** [comment]
Re Aristotle, that one is up to you. Gibbon did the same thing, sometimes referring to the same title three or four different ways. I did try to standardize them to two: one full on at least the initial instance, one shorter version especially for the longer titles, but that was all optional. What I usually did was try to find an edition on IA/Google/Hathi and use what the _actual_ title was (hence the Über on the other issue). But, as with the expanding, that is optional; if he refers to it both ways, you are free to leave them both, or you can standardize them (editorial) if you so choose.
In the case of Hyppo/Hippo, though, it is purely spelling, and we do want to standardize spelling of works. (And, typically, any word; we generally wouldn't want both colour and color in the same work, either, e.g.)

**Comment by irontigran** [comment]
I've found editions in various sources using both names (https://archive.org/details/sophisticis_elenchis_1102_librivox, https://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0086.tlg040, https://openlibrary.org/books/OL16537358M/De_sophisticis_elenchis), so I'll leave both names as Jowett uses them.
