### ISSUE TITLE
Review: Formatting (loosely)

### ISSUE THREAD

**Issue by vr8hub** [irontigran/plato_the-dialogues-of-plato_benjamin_jowett#41]
- [x] Just as some of the quotes you added had colon and semi-colon inside quotes, the text itself also has a number of occurrences. (Search for [;:][”’]) Regardless of who's responsible for them, they go outside the quotes. :) I don't know what editor you use, but this is pretty easy to fix with a single regex search-and-replace (I've had to do it for a number of my productions). Editorial, of course.
- [x] Reductio ad absurdum occurs a number of times in quotes. Because it's always in quotes, I'm guessing the quotes are to indicate it's a foreign phrase? I don't see any other reason to put it in quotes. If so, we can get rid of the quotes. (Editorial) I haven't run across any other instances of this, but if there are other phrases that are consistently quoted like that for the same reason, they should be eliminated as well. (And if it's a foreign phrase that's not in M-W, it should be italicized as a foreign phrase.)
- [x] There are several instances where a normal apostrophe is used in a Greek phrase, e.g. in note-252, where δ’ occurs. I'm fairly certain that should be a normal Greek apostrophe, i.e. the same thing that's over the epsilon in ἐτὶμα earlier in the phrase, so δ᾽ instead. After I saw a couple, I searched for `"grc">[^<]*’[^<]*<` to find the rest. (I had a number of these in Gibbon as well.)
- [x] There's an extraneous period after AD in Timaeus, `… the nineteenth century AD.).`
- [x] There are a number of instances of unsemanticated italics that look they should be either eliminated, or tagged as foreign words/phrases. These are a little tricky to find since unsemanticated italics are used for the speakers in several of the dialogs. Again depending on your editor, you can search for `(?<!<p>)<i>` to find all the instances that aren't at the beginning of a paragraph. You'll still catch some false positives on paragraphs that have id's, but that's a much smaller population, so it's easy to see the rest. For example, _Republic_ has three: tabula rasa, gerousia, and polis. The first and last are in M-W, so the italics should be removed; the middle one is only in M-W unabridged, which doesn't count, so it should be tagged (grc-latn).
- [x] There are a few sentences that are marked as emphasis that look like they are just quotes, e.g. "Until, then, kings are philosophers…" in _Republic_. In these cases they should either be quoted (if it's not confusing with the surrounding text), or be tagged with `<q></q>`, and CSS added to target `<q>` for italics. (I just searched for `<em>.*?</em>`, extracted them to a separate file, and the sentences were immediately obvious. :)
- [x] I just tried to build after pulling all of your changes, and epubcheck doesn't like the `<hr/>` in the middle of the table in Theaetetus. I've successfully avoided producing any drama, so I'm not sure what, if anything, should be done there. The `tr` could be targeted with an nth-of-type; or, since there _happens_ to be an id on that `tr`, it's possible that could be targeted (although SEMoS doesn't allow targeting id's, this is a special case; the id wasn't created _for_ targeting, we would just be taking advantage of the fact it's there).

**Comment by vr8hub** [comment]
I think that's it, Jacob. Again, excellent work! The things I found were all pretty trivial in the scheme of things.

**Comment by irontigran** [comment]
I think I disagree with your assessment of the "Until, then, kings are philosophers..." phrase as a quote.

I count three instances of long emphasized phrases in _Republic_ - two of which are "kings are philosophers" and one is "The son of Ariston (the best) is of the opinion..." I think that all three are famous phrases from Plato and Jowett is deliberately emphasizing them rather than quoting.

In the below example, the paragraph does start with "I said", but that matches the style of the entire dialogue, which is structured as if Socrates is retelling the whole of his conversation with Glaucon to someone else. 

```html
<p id="republic-p-2591">I said: <em>Until philosophers are kings, or the kings and princes of this world have the spirit and power of philosophy, and political greatness and wisdom meet in one, and those commoner natures who pursue either to the exclusion of the other are compelled to stand aside, cities will never have rest from their evils⁠—nor the human race, as I believe⁠—and then only will this our State have a possibility of life and behold the light of day. Such was the thought, my dear Glaucon, which I would fain have uttered if it had not seemed too extravagant; for to be convinced that in no other State can there be happiness private or public is indeed a hard thing.</em></p>
```

**Comment by vr8hub** [comment]
Which is exactly what makes them quotes IMO, just quoted differently. I’m happy for Alex to adjudicate; I don’t always get this stuff right, either. :)

**Comment by irontigran** [comment]
Yes, I suppose it's best to have Alex weigh in then. The short version of my argument is that a similar style of quotes are used throughout the dialogue, but italics are only used in the three places I mentioned, implying special emphasis.

On a different subject, I am also not sure what to do with the Theaetetus `<hr/>`. My (admittedly lazy) first thought is to just remove the `<hr/>` and let the table rows produce separation between the stage direction and the dialogue. Other options: close the table, add the `<hr/>` and the start a new table, or target with CSS as you mentioned.

**Comment by vr8hub** [comment]
I took out the `<hr/>` and rebuilt it, and it looks like this. That looks right to me, so I think that's all that's needed?
<img width="457" alt="image" src="https://user-images.githubusercontent.com/19378955/174399170-62070fe9-ba9f-462b-bdae-d808119c8c62.png">

**Comment by irontigran** [comment]
That sounds good to me - pushed the changes!

**Comment by vr8hub** [comment]
All right, the e-i-c has spoken, the sentences stay emphasis. This issue's done!

**Comment by vr8hub** [comment]
So sorry, I spoke too soon! Re the unsemanticated italics, I only gave examples, there were others (that's why I gave the search criteria). There's at least a Greek phrase in "Sophist," and a bracketed sentence in "Apology". For the Greek phrase, the language tag is on the blockquote, so the italics are redundant. I can't tell why the "Apology" sentence is italicized.

**Comment by irontigran** [comment]
Missed the Greek blockquote in Sophist - fixed now.

For the Apology sentence, it's italicized to match the scans. I wasn't sure what to make of it when I first looked at it, so I defaulted to matching the scan formatting (italics, centered, and set apart from the surrounding paragraphs)

**Comment by vr8hub** [comment]
Yeah, in looking at it further, it looks like it's stating the occasion that the following paragraphs are commenting on. I'm not sure what to do with that, so let's leave it and Alex can suggest something if he wants it changed.
